name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist

      - name: Run Tests
        run: php vendor/bin/pest --colors=always -v --parallel --processes=6

  release:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          token: ${{ secrets.GITHUB_TOKEN }}